export const rooms = [
  {
    id: "suite",
    name: "Suíte",
    description: "Com aproximadamente 24m², as suítes dispõem de espaço amplo, ideal para toda a família e ainda contam com vista parcial para o mar. O conforto está presente por meio de Smart TV, secador de cabelos, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi gratuita.",
    price: "R$ 477,75",
    originalPrice: "R$ 735,00",
    image: "/Quartos/Suíte/Mais claras/IMG_0319.jpg",
    capacity: "4 pessoas",
    size: "24m²",
    beds: "Queen + Beliche",
    bathrooms: 1,
    hasSuite: true,
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Vista para a Cidade"
    ],
    rating: 4.8,
    reviews: 124,
    reservationUrl: "https://book.omnibees.com/hotel/16875/room/99196?c=9190&q=16875&NRooms=1&CheckIn=21092025&CheckOut=22092025&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  },
  {
    id: "standard-triplo", 
    name: "Standard Triplo Solteiro",
    description: "Acomoda até 3 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 13 m², todos os apartamentos dessa categoria possuem vista para a cidade. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    price: "R$ 426,40",
    originalPrice: "R$ 656,00",
    image: "/Quartos/Standard triplo solteiro/62.jpg",
    capacity: "4 pessoas",
    size: "13m²", 
    beds: "Cama de casal + Solteiro",
    bathrooms: 1,
    hasSuite: false,
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless", 
      "Frigobar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista para a Cidade"
    ],
    rating: 4.6,
    reviews: 98,
    reservationUrl: "https://book.omnibees.com/hotel/16875/room/102187?c=9190&q=16875&NRooms=1&CheckIn=21092025&CheckOut=22092025&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  },
  {
    id: "standard-duplo",
    name: "Standard Duplo Casal",
    description: "Acomoda até 2 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 13 m², todos os apartamentos dessa categoria possuem vista para a cidade. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    price: "R$ 341,25",
    originalPrice: "R$ 525,00",
    image: "/Quartos/Standard duplo casal/67.jpeg",
    capacity: "2 pessoas",
    size: "13m²",
    beds: "Cama de casal ou 2 solteiros",
    bathrooms: 1,
    hasSuite: false,
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista para a Cidade"
    ],
    rating: 4.4,
    reviews: 76,
    reservationUrl: "https://book.omnibees.com/hotel/16875/room/99010?c=9190&q=16875&NRooms=1&CheckIn=21092025&CheckOut=22092025&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  },
  {
    id: "standard-triplo-casal",
    name: "Standard Triplo Casal",
    description: "Acomoda até 3 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 15 m², todos os apartamentos dessa categoria possuem vista para a cidade. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    price: "R$ 380,00",
    originalPrice: "R$ 585,00",
    image: "/Quartos/Standard triplo casal/55.jpg",
    capacity: "3 pessoas",
    size: "15m²",
    beds: "Cama de casal + Solteiro",
    bathrooms: 1,
    hasSuite: false,
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista para a Cidade"
    ],
    rating: 4.5,
    reviews: 67,
    reservationUrl: "https://book.omnibees.com/hotel/16875/room/99195?c=9190&q=16875&NRooms=1&CheckIn=21092025&CheckOut=22092025&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  },
  {
    id: "vista-mar",
    name: "Parcial Mar Duplo Solteiro (PNE)",
    description: "Acomoda até 2 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 12 m², todos os apartamentos dessa categoria possuem vista parcial do mar. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    price: "R$ 426,40",
    originalPrice: "R$ 656,00",
    image: "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0154.jpg",
    capacity: "2 pessoas",
    size: "12m²",
    beds: "Cama de casal ou 2 solteiros",
    bathrooms: 1,
    hasSuite: false,
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista Lateral Mar"
    ],
    rating: 4.7,
    reviews: 89,
    reservationUrl: "https://book.omnibees.com/hotel/16875/room/99195?c=9190&q=16875&NRooms=1&CheckIn=21092025&CheckOut=22092025&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  }
]

export const roomDetails = {
  "suite": {
    name: "Suíte",
    capacity: 4,
    beds: "Queen + Beliche",
    bathrooms: 1,
    hasSuite: true,
    price: "477,75",
    originalPrice: "735,00",
    description: "Com aproximadamente 24m², as suítes dispõem de espaço amplo, ideal para toda a família e ainda contam com vista parcial para o mar. O conforto está presente por meio de Smart TV, secador de cabelos, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi gratuita.",
    images: [
      "/Quartos/Suíte/Mais claras/IMG_0319.jpg",
      "/Quartos/Suíte/43.jpg",
      "/Quartos/Suíte/44.jpg",
      "/Quartos/Suíte/45.jpg",
      "/Quartos/Suíte/53.jpg",
      "/Quartos/Suíte/56.jpg",
      "/Quartos/Suíte/57.jpg",
      "/Quartos/Suíte/IMG_0305.jpg",
      "/Quartos/Suíte/IMG_0308.jpg",
      "/Quartos/Suíte/IMG_0311.jpg",
      "/Quartos/Suíte/IMG_0318.jpg",
      "/Quartos/Suíte/IMG_0321.jpg",
      "/Quartos/Suíte/IMG_0327.jpg",
      "/Quartos/Suíte/IMG_0328.jpg",
      "/Quartos/Suíte/IMG_0332.jpg",
      "/Quartos/Suíte/IMG_0334.jpg",
      "/Quartos/Suíte/IMG_0340.jpg",
      "/Quartos/Suíte/IMG_0341.jpg",
      "/Quartos/Suíte/IMG_0342.jpg",
      "/Quartos/Suíte/IMG_8531.jpg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Vista para a Cidade"
    ],
    reservationUrl: "https://book.omnibees.com/hotel/16875/room/99196?c=9190&q=16875&NRooms=1&CheckIn=21092025&CheckOut=22092025&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  },
  "standard-triplo": {
    name: "Standard Triplo Solteiro",
    capacity: 4,
    beds: "Cama de casal + Solteiro",
    bathrooms: 1,
    hasSuite: false,
    price: "426,40",
    originalPrice: "656,00",
    description: "Acomoda até 3 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 13 m², todos os apartamentos dessa categoria possuem vista para a cidade. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    images: [
      "/Quartos/Standard triplo solteiro/62.jpg",
      "/Quartos/Standard triplo solteiro/IMG_0222.jpg",
      "/Quartos/Standard triplo solteiro/IMG_0224.jpg",
      "/Quartos/Standard triplo solteiro/IMG_0227.jpg",
      "/Quartos/Standard triplo solteiro/IMG_0231.jpg",
      "/Quartos/Standard triplo solteiro/IMG_0232.jpg",
      "/Quartos/Standard triplo solteiro/IMG_0234.jpg",
      "/Quartos/Standard triplo solteiro/IMG_0237.jpg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Frigobar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista para a Cidade"
    ],
    reservationUrl: "https://book.omnibees.com/hotel/16875/room/102187?c=9190&q=16875&NRooms=1&CheckIn=21092025&CheckOut=22092025&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  },
  "standard-duplo": {
    name: "Standard Duplo Casal",
    capacity: 2,
    beds: "Cama de casal ou 2 solteiros",
    bathrooms: 1,
    hasSuite: false,
    price: "341,25",
    originalPrice: "525,00",
    description: "Acomoda até 2 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 13 m², todos os apartamentos dessa categoria possuem vista para a cidade. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    images: [
      "/Quartos/Standard duplo casal/67.jpeg",
      "/Quartos/Standard duplo casal/IMG_0196.jpg",
      "/Quartos/Standard duplo casal/IMG_0198.jpg",
      "/Quartos/Standard duplo casal/IMG_0200.jpg",
      "/Quartos/Standard duplo casal/IMG_0201.jpg",
      "/Quartos/Standard duplo casal/IMG_0202.jpg",
      "/Quartos/Standard duplo casal/IMG_0204.jpg",
      "/Quartos/Standard duplo casal/IMG_0206.jpg",
      "/Quartos/Standard duplo casal/IMG_0211.jpg",
      "/Quartos/Standard duplo casal/IMG_0212.jpg",
      "/Quartos/Standard duplo casal/IMG_0214.jpg",
      "/Quartos/Standard duplo casal/IMG_0215.jpg",
      "/Quartos/Standard duplo casal/IMG_0217.jpg",
      "/Quartos/Standard duplo casal/IMG_0219.jpg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista para a Cidade"
    ],
    reservationUrl: "https://book.omnibees.com/hotel/16875/room/99010?c=9190&q=16875&NRooms=1&CheckIn=21092025&CheckOut=22092025&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  },
  "standard-triplo-casal": {
    name: "Standard Triplo Casal",
    capacity: 3,
    beds: "Cama de casal + Solteiro",
    bathrooms: 1,
    hasSuite: false,
    price: "380,00",
    originalPrice: "585,00",
    description: "Acomoda até 3 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 15 m², todos os apartamentos dessa categoria possuem vista para a cidade. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    images: [
      "/Quartos/Standard triplo casal/55.jpg",
      "/Quartos/Standard triplo casal/IMG_0239.jpg",
      "/Quartos/Standard triplo casal/IMG_0243.jpg",
      "/Quartos/Standard triplo casal/IMG_0248.jpg",
      "/Quartos/Standard triplo casal/IMG_0250.jpg",
      "/Quartos/Standard triplo casal/IMG_0251.jpg",
      "/Quartos/Standard triplo casal/IMG_0255.jpg",
      "/Quartos/Standard triplo casal/IMG_0257.jpg",
      "/Quartos/Standard triplo casal/IMG_0258.jpg",
      "/Quartos/Standard triplo casal/IMG_8487.jpg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista para a Cidade"
    ],
    reservationUrl: "https://book.omnibees.com/hotel/16875/room/99195?c=9190&q=16875&NRooms=1&CheckIn=21092025&CheckOut=22092025&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  },
  "vista-mar": {
    name: "Parcial Mar Duplo Solteiro (PNE)",
    capacity: 2,
    beds: "Cama de casal ou 2 solteiros",
    bathrooms: 1,
    hasSuite: false,
    price: "426,40",
    originalPrice: "656,00",
    description: "Acomoda até 2 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 12 m², todos os apartamentos dessa categoria possuem vista parcial do mar. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    images: [
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0154.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0155.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0159.JPG",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0160.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0162.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0163.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0164.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0167.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0170.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0171.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0177.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0184.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0185.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0189.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0192.jpg",
      "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0194.jpg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista Lateral Mar"
    ],
    reservationUrl: "https://book.omnibees.com/hotel/16875/room/99195?c=9190&q=16875&NRooms=1&CheckIn=21092025&CheckOut=22092025&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  }
}
