export const rooms = [
  {
    id: "standard-duplo",
    name: "Standard Duplo",
    description: "Acomoda até 2 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 13 m², todos os apartamentos dessa categoria possuem vista para a cidade. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    price: "R$ 341,25",
    originalPrice: "R$ 525,00",
    image: "/Quartos/Standard duplo casal/67.jpeg",
    capacity: "2 pessoas",
    size: "13m²",
    beds: "Cama de casal ou 2 solteiros",
    bathrooms: 1,
    hasSuite: false,
    bedOptions: "Disponível como casal ou solteiro",
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista para a Cidade"
    ],
    rating: 4.4,
    reviews: 76,
    reservationUrl: "https://app.otabuilder.com/tinttohotel",
  },
  {
    id: "standard-triplo", 
    name: "Standard Triplo",
    description: "Acomoda até 3 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 13 m², todos os apartamentos dessa categoria possuem vista para a cidade. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    price: "R$ 426,40",
    originalPrice: "R$ 656,00",
    image: "/Quartos/Standard triplo solteiro/62.jpg",
    capacity: "3 pessoas",
    size: "13m²", 
    beds: "Cama de casal + Solteiro",
    bathrooms: 1,
    hasSuite: false,
    bedOptions: "2 opções: 3 camas de solteiro ou 1 cama de casal + 1 solteiro",
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless", 
      "Frigobar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista para a Cidade"
    ],
    rating: 4.6,
    reviews: 98,
    reservationUrl: "https://app.otabuilder.com/tinttohotel",
  },
  {
    id: "vista-parcial-mar",
    name: "Vista Parcial Mar",
    description: "Acomoda até 2 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 12 m², todos os apartamentos dessa categoria possuem vista parcial do mar. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    price: "R$ 426,40",
    originalPrice: "R$ 656,00",
    image: "/Quartos/Parcial mar duplo solteiro (PNE)/Claras/IMG_0154.jpg",
    capacity: "2 pessoas",
    size: "12m²",
    beds: "Cama de casal ou 2 solteiros",
    bathrooms: 1,
    hasSuite: false,
    bedOptions: "Disponível como casal ou solteiro",
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista Lateral Mar"
    ],
    rating: 4.7,
    reviews: 89,
    reservationUrl: "https://app.otabuilder.com/tinttohotel",
  },
  {
    id: "suite",
    name: "Suíte",
    description: "Com aproximadamente 24m², as suítes dispõem de espaço amplo, ideal para toda a família e ainda contam com vista parcial para o mar. O conforto está presente por meio de Smart TV, secador de cabelos, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi gratuita.",
    price: "R$ 477,75",
    originalPrice: "R$ 735,00",
    image: "/Quartos/Suíte/Mais claras/IMG_0319.jpg",
    capacity: "5 pessoas",
    size: "24m²",
    beds: "Queen + Triliche",
    bathrooms: 1,
    hasSuite: true,
    bedOptions: "Configuração fixa",
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Vista para a Cidade"
    ],
    rating: 4.8,
    reviews: 124,
    reservationUrl: "https://app.otabuilder.com/tinttohotel",
  }
]

export const roomDetails = {
  "standard-duplo": {
    name: "Standard Duplo",
    capacity: 2,
    beds: "Cama de casal ou 2 solteiros",
    bathrooms: 1,
    hasSuite: false,
    price: "341,25",
    originalPrice: "525,00",
    description: "Acomoda até 2 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 13 m², todos os apartamentos dessa categoria possuem vista para a cidade. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    images: [
      "/Quartos/Standard duplo casal/67.jpeg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista para a Cidade"
    ],
    reservationUrl: "https://app.otabuilder.com/tinttohotel",
  },
  "standard-triplo": {
    name: "Standard Triplo",
    capacity: 3,
    beds: "Cama de casal + Solteiro",
    bathrooms: 1,
    hasSuite: false,
    price: "426,40",
    originalPrice: "656,00",
    description: "Acomoda até 3 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 13 m², todos os apartamentos dessa categoria possuem vista para a cidade. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    images: [
      "/Quartos/Standard triplo solteiro/62.jpg",
      "/Quartos/Standard triplo casal/IMG_0250.jpg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Frigobar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista para a Cidade"
    ],
    reservationUrl: "https://app.otabuilder.com/tinttohotel",
  },
  "vista-parcial-mar": {
    name: "Vista Parcial Mar",
    capacity: 2,
    beds: "Cama de casal ou 2 solteiros",
    bathrooms: 1,
    hasSuite: false,
    price: "426,40",
    originalPrice: "656,00",
    description: "Acomoda até 2 adultos + 1 criança cortesia (até 5 anos). Com aproximadamente 12 m², todos os apartamentos dessa categoria possuem vista parcial do mar. O conforto está presente por meio de Smart TV, secador de cabelo, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi.",
    images: [
      "/Quartos/Parcial mar duplo solteiro (PNE)/IMG_0160.jpg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Apartamento para não Fumantes",
      "Vista Lateral Mar"
    ],
    reservationUrl: "https://app.otabuilder.com/tinttohotel",
  },
  "suite": {
    name: "Suíte",
    capacity: 5,
    beds: "Queen + Triliche",
    bathrooms: 1,
    hasSuite: true,
    price: "477,75",
    originalPrice: "735,00",
    description: "Com aproximadamente 24m², as suítes dispõem de espaço amplo, ideal para toda a família e ainda contam com vista parcial para o mar. O conforto está presente por meio de Smart TV, secador de cabelos, telefone com linha direta, cofre individual, frigobar, ar condicionado e internet wi-fi gratuita.",
    images: [
      "/Quartos/IMG_0308.jpg",
      "/Quartos/IMG_0341.jpg",
      "/Quartos/IMG_0328.jpg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar",
      "Telefone com linha direta",
      "Smart TV",
      "Secador de cabelo",
      "Banheiro privado",
      "Vista para a Cidade"
    ],
    reservationUrl: "https://app.otabuilder.com/tinttohotel",
  }
}
